spring:
  application:
    name: concept-map-application
  
  # Database Configuration - Using SQLite for development
  datasource:
    url: jdbc:sqlite:conceptmap.db
    driver-class-name: org.sqlite.JDBC
    username: ""
    password: ""
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.community.dialect.SQLiteDialect
  
  # JSON Configuration
  jackson:
    serialization:
      indent-output: true
    property-naming-strategy: SNAKE_CASE

# Server Configuration
server:
  port: 8080

# CORS Configuration
cors:
  allowed-origins:
    - http://localhost:3000
    - http://localhost:3157
    - http://localhost:8080
    - http://127.0.0.1:3000
    - http://127.0.0.1:8080
    - http://127.0.0.1:3157
  allowed-methods:
    - GET
    - POST
    - PUT
    - DELETE
    - OPTIONS
  allowed-headers: "*"
  allow-credentials: true

# Logging Configuration
logging:
  level:
    edu.ewu.cscd211.conceptmap: DEBUG
    org.springframework.web: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
